### ISSUE TITLE
Warning where nullability annotation would be redundant (async Task)

### ISSUE THREAD

**Issue by starkcolin** [bkoelman/ResharperCodeContractNullability#20]
A nullability warning (RNUL) on a method with a signature async Task is redundant, as the Task object returned from this method can never be null.

When the method return type is Task<T> (where T is a reference type), the annotation ItemNotNull/ItemCanBeNull makes sense, but the NotNull/CanBeNull annotation adds no value in this case.  When the return type is simply Task, neither of those annotations make sense.

**Comment by bkoelman** [comment]
Nice catch!

I agree that RNUL should be removed from async methods.

For non-async methods the existing rules should still apply, I believe. Since returning a null task is allowed, so annotating them makes resharper report potential warnings:

![image](https://cloud.githubusercontent.com/assets/10324372/13345180/1a456524-dc5d-11e5-9631-78eb6c531a9b.png)

**Comment by starkcolin** [comment]
Agreed that the warning should still be displayed for non-async methods.

**Comment by bkoelman** [comment]
This fix is included in https://github.com/bkoelman/ResharperCodeContractNullability/releases/tag/v1.0.5.
